# -*- coding: utf-8 -*-
"""classificacao_transfer_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ca8L6Bt6smFvYLWhel58RDOD1zqaUOGZ

# Transferência de aprendizagem para classificação de imagens

## Transferência de aprendizagem

* **O aprendizado de transferência consiste em pegar recursos aprendidos em um problema e aproveitá-los em um problema novo e semelhante.**
* **Neste exemplo irei aproveitar o modelo [MobileNetV2](https://keras.io/api/applications/mobilenet/#mobilenetv2-function).**
* **O método geralmente é feito para tarefas em que seu conjunto de dados tem poucos dados para treinar um modelo do zero.**
* **Devido ao desempenho e limitação de hardware optei pelo modelo MobileNetV2, pois nas mil imagens testadas obtive uma acurácia acima de 95%.**

### Importação das bibliotecas
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras.models import Model
from keras.layers import Input, Dense, GlobalAveragePooling2D, Dropout
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile
import numpy as np
import cv2
import pandas as pd
from google.colab.patches import cv2_imshow
tf.__version__

"""### Carregamento das imagens

* **Para este estudo, serão utilizados 4 mil imagens de forma aleatória e balanceada entre gatos e cães para o treinamento do modelo.**
* **Para o Teste(validação) foram separadas mil imagens dividas entre gatos e cães.**
* **O arquivo no formato zip está disponível para download [aqui](https://drive.google.com/file/d/10Zc6nKXZQDpWEj6zdyIW7ULCQ8ISd2B0/view).**
* **As imagens foram selecionadas à partir [Kaggle Cats and Dogs](https://www.microsoft.com/en-us/download/confirmation.aspx?id=54765).**
"""

#Conectando ao google drive.
from google.colab import drive
drive.mount('/content/drive')

# Realizando a extração do arquivo zip.
path = '/content/drive/MyDrive/datasets/cat_dog.zip'
zip_object = zipfile.ZipFile(file=path, mode='r')
zip_object.extractall('./')
zip_object.close()

#Visualizando um imagem da pasta de treinamento cat.
tf.keras.preprocessing.image.load_img('/content/cat_dog/training_set/cat/cat.3.jpg')

# visualizando uma imagem da pasta de treinamento dog.
tf.keras.preprocessing.image.load_img('/content/cat_dog/training_set/dog/dog.3.jpg')

"""### Base de dados de treinamento e teste

#### Como usar o aumento de dados aleatórios
* **Quando você não tem um grande conjunto de dados de imagem, é uma boa prática introduzir diversidade de amostra artificialmente aplicando transformações aleatórias, porém realistas, às imagens de treinamento, como inversão horizontal aleatória ou pequenas rotações aleatórias e zoom nas imagens. Isso ajuda a expor o modelo a diferentes aspectos dos dados de treinamento enquanto diminui o overfitting.**
* **Precisamos também normalizar e redimensionar todas as imagens para o mesmo padrão, para isso irei utilizar o método ImageDataGenerator conforme abaixo.**
"""

# realizando o redimensionamento e a normalização no conjunto de treinamento.
gerador_treinamento = ImageDataGenerator(rescale=1./255, rotation_range=7, horizontal_flip=True, zoom_range=0.2)
dataset_treinamento = gerador_treinamento.flow_from_directory('/content/cat_dog/training_set',
                                                        target_size = (128, 128),
                                                        batch_size = 128,
                                                        class_mode = 'categorical',
                                                        shuffle = True)

"""* **Foram encontradas 4000 imagens e 2 classes(cat e dog).**

* **Visualizando o comportamento das imagens apenas para uma melhor compreensão das alterações realizadas**.
"""

# Alterando as imagens.
datagen = ImageDataGenerator(
        rotation_range=7, # Rotação
        zoom_range=0.2, # aplicano 20% de zoom
        horizontal_flip=True, # horizontal flip
        brightness_range=[0.2,1.2]) # brilho

# Imagem sem alteração.
datanorm = ImageDataGenerator()

# Conjunto com alterações
treino_alterado = datagen.flow_from_directory(
                  '/content/cat_dog/training_set',
                  target_size=(400, 400), # padronizando todas as imagens
                  color_mode="rgb", # imagem colorida
                  batch_size=1, # numero de imagens extraída por batch
                  class_mode="binary", # classes
                  seed=2020 # para que os resultados sejam reproduzidos
                  )

# Conjunto sem sofrer alterações
treino_normal = datanorm.flow_from_directory(
                  '/content/cat_dog/training_set',
                  target_size=(400, 400),
                  color_mode="rgb",
                  batch_size=1,
                  class_mode="binary",
                  seed=2020
                  )

fig, ax = plt.subplots(nrows=2, ncols=4, figsize=(15,15))

# Plotando 5 imagens
for i in range(4):

  # convertendo a imagem para inteiro
  image = next(treino_alterado)[0].astype('uint8')
  image2 = next(treino_normal)[0].astype('uint8')

  # alterando o formato (1, 200, 200, 3) para (200, 200, 3) para plotar a imagem
  image = np.squeeze(image)
  image2 = np.squeeze(image2)


  # plotando as imagens
  ax[0,i].imshow(image2)
  ax[0,i].set_title('Imagem original')
  ax[0,i].axis('off')
  ax[1,i].imshow(image)
  ax[1,i].set_title('Imagem alterada')
  ax[1,i].axis('off')

"""* **Podemos ver que além do redimensionamento de todas as imagens para 128 x 128, foram criadas novas imagens de forma invertida, com uma leve rotação, outras com 20% de zoom e com menos brilho etc...**"""

# realizando o redimensionamento e a normalização no conjunto de teste.
gerador_teste = ImageDataGenerator(rescale=1./255)
dataset_teste = gerador_teste.flow_from_directory('/content/cat_dog/test_set',
                                                     target_size = (128, 128),
                                                     batch_size = 1,
                                                     class_mode = 'categorical',
                                                     shuffle = False)

"""* **Foram localizadas 1000 imagens e 2 classes para o conjunto de teste.**

### Rede neural pré-treinada

* **Conforme mencionado, vamos utilizar o modelo 'MobileNetV2' que já foi treinado para outros fins, assim não precisamos implementar do zero, o que seria impraticável devido ao poder computacional disponível e a quantidade de dados, certamente não obteriamos um resultado equivalente.**
* **A idéia é utilizar todos os pesos das camadas do modelo que já foi treinado(know-how) e implementar apenas as camadas finais para o objetivo proposto, que nesse caso é saber identificar se o animal é um gato ou cão.**
"""

# Carregando o modelo base MobileNetV2.
modelo_base = tf.keras.applications.MobileNetV2(weights='imagenet', include_top=False,
                                               input_shape = (128,128,3))

# informações das camadas do modelo base.
modelo_base.summary()

# visualizando a quantidade de camadas que o modelo  possui.
len(modelo_base.layers)

# Congelando os pesos das camadas para serem reaproveitadas.
for layer in modelo_base.layers:
  layer.trainable = False

"""* **O modelo possui 154 camadas que iremos reaproveitar, para isso foi utilizado o parametro False em layer.trainable para fixar os pesos das camadas.**

### Camada densa personalizada
"""

# acessando a ultima camada do modelo base, pois após ela iremos adicionar a estrutura densa.
modelo_base.output

"""* **A última camada possui 1280 conexões. Para realizar a ligação com a nova camada iremos utilizar a metade dessas conexões.**
* **Dropout irá descartar 20% das conexões para próxima camada, isso reduz o overfitting.**
* **Ao final criamos uma camada densa de 2 conexões para classificação (gato,cão).**
"""

(1280 + 2) / 2

head_model = modelo_base.output
head_model = tf.keras.layers.GlobalAveragePooling2D()(head_model)
head_model = Dense(641, activation = 'relu')(head_model)
head_model = Dropout(0.2)(head_model)
head_model = Dense(641, activation = 'relu')(head_model)
head_model = Dropout(0.2)(head_model)
head_model = Dense(2, activation = 'softmax')(head_model)

"""### Construção e treinamento da rede neural"""

# Realizando a ligação entre o modelo base e as camadas que foram implementadas.
network = Model(inputs = modelo_base.input, outputs = head_model)

# visualizando as informações das camadas.
network.summary()

# Adicionamos as 6 camadas finais ao modelo.
len(network.layers)

# compilando o modelo.
network.compile(loss = 'categorical_crossentropy', optimizer='Adam',
                metrics = ['accuracy'])

# Realizando o treimanto com 5 epocas.
historico = network.fit(dataset_treinamento, epochs=5)

"""### Avaliação da rede neural"""

# Avaliando a rede neural com o conjunto de teste.
network.evaluate(dataset_teste)

# Realizando as previsões no conjunto de teste.
previsoes = network.predict(dataset_teste)
previsoes

# previsões para o conjunto de teste.
previsoes = np.argmax(previsoes, axis = 1)
previsoes[:10] # 10 primeiros registros.

# classificação real do conjunto de teste.
dataset_teste.classes[:10] # 10 primeiros registros

# usando a função de acurária do sklearn apenas para comparar se os resultados estão corretos.
from sklearn.metrics import accuracy_score
accuracy_score(dataset_teste.classes, previsoes)

network.evaluate(dataset_teste)

"""* **Conforme o resultado, tivemos 96% de acurácia no conjunto de teste.**
* **Vamos plotar o gráfico da matriz de conjunção.**
"""

dataset_treinamento.class_indices

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(dataset_teste.classes, previsoes)
# figure
fig, ax = plt.subplots(figsize=(7, 7))
# plot heatmap
sns.heatmap(cm, cmap="Blues",annot=True,fmt=".1f",cbar=False)
# xticks
ax.xaxis.tick_top()
xticks_labels = ['Cat', 'Dog']
plt.xticks(np.arange(2) + .5, labels=xticks_labels)

# yticks
ax.yaxis.tick_left()
yticks_labels = ['Cat', 'Dog']
plt.yticks(np.arange(2) + .5, labels=yticks_labels)
# axis labels
plt.xlabel('')
plt.ylabel('')
# title
title = 'Matriz de confusão - Classificação de Cães e Gatos'.upper()
plt.title(title, loc='left')
plt.show()

"""* **Pela matriz podemos ver que o modelo acertou 492 gatos dos 500 e errou 8.**
* **O modelo acertou 468 Cães dos 500 e classificou 32 de forme equivocada.**

"""

from sklearn.metrics import classification_report
print(classification_report(dataset_teste.classes, previsoes))

"""* **O modelo teve um resultado bem satisfatório para detectar ambas imagens.**

# Salvar e carregar a rede neural
"""

# Salvando os parametros do modelo.
model_json = network.to_json()
with open('network.json','w') as json_file:
  json_file.write(model_json)

# Salvando os pesos das camadas.
from keras.models import save_model
network_saved = save_model(network, '/content/weights.hdf5')

# visualizando o arquivo.json
with open('network.json', 'r') as json_file:
  json_saved_model = json_file.read()
json_saved_model

#Carregando o modelo salvo.
network_loaded = tf.keras.models.model_from_json(json_saved_model)
network_loaded.load_weights('weights.hdf5')
network_loaded.compile(loss = 'categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])

# conferindo as informações das camadas.
network_loaded.summary()

"""* **Com o modelo salvo podemos criar uma aplicação para consumir o modelo e classificar imagens de cães e gatos.**

# Classificação de uma única imagem

* **Vamos testar em uma única imagem para simular uma aplicação.**
"""

# carregando uma imagem
imagem = cv2.imread('/content/cat_dog/test_set/dog/dog.3508.jpg')

cv2_imshow(imagem)

# Alterando para o tamanho padrão e rotacioando a imagem para dificultar a classificação.
imagem = cv2.resize(imagem, (128, 128))
imagem = cv2.rotate(imagem, cv2.ROTATE_90_COUNTERCLOCKWISE)
cv2_imshow(imagem)

# Normalizando a imagem.
imagem = imagem / 255
imagem

# Conferindo o formato
imagem.shape

# necessário realizar o reshape para que o modelo entenda o formato.
imagem = imagem.reshape(1,128,128,3)

# Realizando a previsão.
previsao = network_loaded(imagem)
previsao

previsao = np.argmax(previsao)
previsao

dataset_teste.class_indices

if previsao == 0:
  print('O modelo identificou que o animal é um: Gato')
else:
  print('O modelo identificou que o animal é um: Cão')

"""* **Veja que mesmo rotacionando a imagem o modelo conseguiu prever corretamente a imagem.**
* **Podemos tentar melhorar a precisão acrescentando uma técnica de ajuste fino, porém ficará para um outro estudo.**
"""