# -*- coding: utf-8 -*-
"""pipeline_python_ia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14io3mN8NVpG8ruvG0-AwylpRHH8A5GC_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Criando variável para armazenar o link da Fake API.
sdw2023_api_url = 'https://loweringly-unmellifluent-yamileth.ngrok-free.dev'

"""#Extract

Extrair a lista de IDs de usuário a partir do arquivo CSV. Para cada ID, foi feita uma requisição GET para obter os dados do usuário correspondente.

Utilização de Fake API local exposta na internet com a criação de um túnel público via ngrok.
"""

#TODO Extrair os IDs do arquivo csv.
df = pd.read_csv('sdw2023.csv')
user_ids = df['UserID'].tolist()
print(user_ids)

#TODO Obter os dados de cada ID usando a API da Santander Dev Week 2023
import requests
import json

def get_user(id):
  response = requests.get(f'{sdw2023_api_url}/users/{id}')
  return response.json() if response.status_code == 200 else None

users = [user for id in user_ids if (user := get_user(id)) is not None]
print(json.dumps(users, indent=2))

"""#Transform

Utilização de API do Gemini para gerar uma mensagem de marketing personalizada para cada usuário.
"""

#TODO Implementar a integração com o Google Gemini.
from google.colab import drive
drive.mount('/content/drive')

from dotenv import load_dotenv
import os

load_dotenv('/content/drive/MyDrive/chave_api_gemini.env') #Deixei a chave oculta em um doc .env, para não ficar exposta no código.
api_key = os.getenv("GOOGLE_API_KEY")

from google import genai
from google.genai import types
client = genai.Client(api_key=api_key)

def generate_ai_news(user):
  completion = client.models.generate_content(
    model="gemini-2.5-flash",
    config=types.GenerateContentConfig(
        system_instruction="Você é um especialista de marketing que trabalha faz anos para uma agência bancária."
    ),
    contents=f"Crie uma mensagem para {user['name']} sobre a importância dos investimentos. A mensagem deve ser feita levando em consideração o perfil de cliente baseado no seu saldo em conta de {user['account']['balance']} reais e seu limite do cartão de {user['card']['limit']} reais, porém, não fale de forma explícita o valor que o cliente tem ou insinuar que ele tem pouco ou muito dinheiro. A mensagem não deve ter mais de 100 caracteres."
  )
  return completion.text

for user in users:
  user.setdefault("news", [])
  news = generate_ai_news(user)
  print(news)
  user['news'].append({
      "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg",
      "description": news
  })

with open("users_with_news.json", "w", encoding="utf-8") as f:
    json.dump(users, f, indent=2, ensure_ascii=False)

"""#Load

Atualizar a lista de "news" de cada usuário na API com a nova mensagem gerada.
"""

#TODO Atualizar os usuários na API da Santander Dev Week 2023 com os dados enriquecidos.
def update_user(user):
  response = requests.put(f"{sdw2023_api_url}/users/{user["id"]}", json=user)
  return True if response.status_code == 200 else False

for user in users:
  success = update_user(user)
  print(f"User {user['name']} updated? {success}!")